version: '3'

services:
  db:
    image: postgres:12.0
    environment:
      POSTGRES_DB: mspurchasing
      POSTGRES_USER: mspurchasing
      POSTGRES_PASSWORD: mspurchasing
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:3.2.8
    ports:
      - 6379:6379

  mspurchasing:
    build: ./mspurchasing
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mspurchasing:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  mswebclient:
    build: ./mswebclient
    command: npm run serve
    volumes:
      - ./mswebclient:/code
    ports:
      - 8080:8080
