version: '3'

services:
  db:
    image: postgres:12.0
    container_name: conids-db
    restart: always
    environment:
      POSTGRES_DB: mspurchasing
      POSTGRES_USER: mspurchasing
      POSTGRES_PASSWORD: mspurchasing
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:3.2.8
    container_name: conids-redis
    ports:
      - 6379:6379

  mspurchasing:
    build: ./mspurchasing
    container_name: conids-backend
    command: bash -c 'while !</dev/tcp/conids-db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./mspurchasing:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  mswebclient:
    build: ./mswebclient
    container_name: conids-frontend
    command: npm run dev #sleep 1000 
    volumes:
      - ./mswebclient:/code
    ports:
      - 5173:5173
