# Generated by Django 4.2.1 on 2023-06-02 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('internal_reference', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('sales_price', models.FloatField()),
                ('cost', models.FloatField()),
                ('quantity_on_hand', models.IntegerField()),
                ('forecasted_quantity', models.IntegerField()),
                ('activity_exception_decoration', models.CharField(max_length=255)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_a_company', models.BooleanField(default=False)),
                ('related_company', models.CharField(max_length=255)),
                ('address_type', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OdooBot', max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=255)),
                ('order_deadline', models.DateTimeField()),
                ('activities', models.TextField()),
                ('source_document', models.TextField()),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.priority')),
                ('product_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.product')),
                ('purchase_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.responsible')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.responsible'),
        ),
    ]
